services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/nutrabiotics_test_db
      - JWT_SECRET=2ec045153b9909c2ce8af6752cc65636
      - JWT_EXPIRATION=5h
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    environment:
      - VITE_API_URL=http://backend:3000
    depends_on:
      - backend

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"  # HOST:CONTAINER
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local
